/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{js,ts,jsx,tsx,html}"],
  theme: {
    extend: {},
    colors: {
      trello: "#9EACBA",
      trelloColor1: "#221776",
      trelloColor2: "#95326c",
      trelloNav: "#1d2125",
      gridHoverColor: "#b2bdca3d",
      createButtonColor: "#579dff",
      profileColor: "#202f49",
      profileBgColor: "#fe981e",
      transparent: "transparent",
      inputColor: "#22272b",
      inputPlaceholderColor: "#535c66",
      inputBorderColor: "#353d45",
      buttonHoverColor: "#8db7f1",
      inputShadow: "5px 5px #fbfbfb",
      taskNavBgColor: "#2c16598e",
      titleColor: "#fff",
      titleHoverColor: "rgba(166, 177, 180, 0.199)",
      starColor: "#e2b203",
      boardColor: "#dfe1e6",
      cardBgColor: "black",
      borderColor: "blue",
      tooltipBgColor: "black",
      tooltipColor: "#9fadbc",
    },
  },
  plugins: [],
};
